Adds a workload status command
cofide/cofidectl pull request #22
Opened 2024-11-15 08:54 UTC by meyskens

`cofidectl workload status foo --pod-name foo-pod --namespace bar --trust-zone foo`

Initially, this command will take a workload name, with pod name, namespace and trust-zone as flags, and use Maartje's "attest-me" implementation via a debug container to return human-readable cert information with the CLI.

As a follow-up, I'd like to make it simpler to reference the workload (ideally a single argument) and for pod and cluster info be inferred, but that'll depend on how we handle 'workloads' and will need some additional thought.

2024-11-21 10:39 UTC, mattbates commented
This PR depends on cofide/cofidectl-debug-container also being opened up. There are small improvements to be made to it in the meantime (eg some simple docs and a build script).

2024-11-22 10:44 UTC, markgoddard reviewed
Looking good

2024-11-22 10:44 UTC, markgoddard commented on cmd/cofidectl/cmd/workload/workload.go
> +		Short: "List or introspect the status of workloads in a trust zone or discover candidate workloads",
```suggestion
		Short: "List, introspect or discover the status of workloads in a trust zone",
```

2024-11-22 10:44 UTC, markgoddard commented on cmd/cofidectl/cmd/workload/workload.go
> +This command will display the status of workloads in the Cofide configuration state.
```suggestion
This command will display the status of workloads in a trust zone.
```

2024-11-22 10:44 UTC, markgoddard commented on cmd/cofidectl/cmd/workload/workload.go
> +	client, err := kubeutil.NewKubeClientFromSpecifiedContext(kubeConfig, *trustZone.KubernetesContext)
The getter handles nil pointers etc.
```suggestion
	client, err := kubeutil.NewKubeClientFromSpecifiedContext(kubeConfig, trustZone.GetKubernetesContext())
```

2024-11-22 10:44 UTC, markgoddard commented on cmd/cofidectl/cmd/workload/workload.go
> +	workloadName string // used to pass arg[0]
This doesn't seem to be used.

2024-11-22 10:44 UTC, markgoddard commented on internal/pkg/workload/workload.go
> +				Message: "Error waiting for ephemeral debug container to complete",
```suggestion
				Message: "Timed out waiting for ephemeral debug container to complete",
```

2024-11-22 11:32 UTC, markgoddard approved these changes

2024-11-25 09:31 UTC, nialdaly approved these changes

2024-11-25 09:42 UTC, mattbates commented
@nialdaly thanks for the approval, you've verified everything works for you?

2024-11-25 10:28 UTC, nialdaly commented
It worked well for me:
```
./cofidectl workload status --namespace test --pod-name client-6c7f5bf7dc-mzkh4 --trust-zone test
✅ Complete: Successfully executed ephemeral debug container in client-6c7f5bf7dc-mzkh4

Trust bundles received
* spiffe://cofide-a.test
    Certificate "CD:11:C2:66:50:4C:A9:D6:9E:99:9B:DA:CB:CE:6A:0F:C1:44:54:53:D4:D8:70:A4:F0:37:D4:FB:40:24:7E:92"
    is a CA certificate
    valid from "2024-11-25T09:49:43Z" to "2024-11-25T21:49:53Z"
    Subject: SERIALNUMBER=326417798281054835965078118436728917784,CN=example.org,O=Example,C=ARPA
    DNS names: spiffe://cofide-a.test
    Signature algorithm: SHA256-RSA
    Issuer: SERIALNUMBER=326417798281054835965078118436728917784,CN=example.org,O=Example,C=ARPA

SVIDs received
* spiffe://cofide-a.test/ns/test/sa/default
    Certificate "80:1F:DA:62:A7:A7:A1:53:A5:D4:DC:08:36:AB:FF:DF:63:55:25:2F:11:4D:EA:99:84:FE:FF:9B:49:C2:6B:43"
    valid from "2024-11-25T10:26:33Z" to "2024-11-25T14:26:43Z"
    Subject: O=SPIRE,C=US
    DNS names: spiffe://cofide-a.test/ns/test/sa/default
    Signature algorithm: SHA256-RSA
    Issuer: SERIALNUMBER=326417798281054835965078118436728917784,CN=example.org,O=Example,C=ARPA
    SVID verified against trust bundle
```

2024-11-28 11:27 UTC, jsnctl commented
Hold off until debug container image hosting story is finalised

2024-12-19 16:21 UTC, meyskens commented
Now using the GHCR image. CI is passing again ready for a last re-read before merging

2024-12-20 09:49 UTC, markgoddard requested changes
I think this change has gone back to an earlier version prior to addressing review feedback. The commit that was approved was e27f3f8.

2024-12-20 09:52 UTC, markgoddard commented
I think a bit of git magic will help here:
```
git checkout e27f3f8
git merge-base origin/main HEAD
git reset --soft $(git merge-base origin/main HEAD)
git status
git diff --cached 
git commit -m "New commit message here"
git rebase origin/main
```

2024-12-20 13:17 UTC, meyskens commented
@markgoddard git surgery should be done! hope it worked out well...

2024-12-23 17:08 UTC, markgoddard approved these changes

2024-12-23 17:14 UTC, markgoddard commented
I reworked it to be closer to the last approved patch and to use the statusspinner.

2024-12-23 17:28 UTC, merged